# Generated by Django 6.0.2 on 2026-08-01 19:22

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path, validators=[accounts.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('resume', models.FileField(blank=True, null=True, upload_to=accounts.models.resume_upload_path, validators=[accounts.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('github_url', models.URLField(blank=True, max_length=300, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=300, null=True)),
                ('website_url', models.URLField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('available_for_work', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('user__username',),
                'indexes': [models.Index(fields=['available_for_work'], name='available_for_work_idx'), models.Index(fields=['location'], name='profile_location_idx')],
            },
        ),
    ]
