# Generated by Django 6.0.7 on 2026-08-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_created_at_profile_updated_at'),
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='portfolio.skill'),
        ),
    ]
