# Generated by Django 6.0.7 on 2026-08-07 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jop_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
