# Generated by Django 6.0.7 on 2026-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_jop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=150),
        ),
    ]
