# Generated by Django 6.0.7 on 2026-08-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_about_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About',
            new_name='about',
        ),
    ]
