# Generated by Django 6.1 on 2026-08-14 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_about_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, dots, underscores, and hyphens.', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
    ]
