# Generated by Django 6.0.7 on 2026-08-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_blogpost_content',
        ),
    ]
