# Generated by Django 6.0.2 on 2026-08-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_created_at_profile_updated_at'),
        ('portfolio', '0002_skill_created_at_skill_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique SEO-friendly slug generated automatically from the project title.', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='in_progress', max_length=20)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('source_code_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this project in featured sections.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('title',),
                'indexes': [models.Index(fields=['title'], name='portfolio_p_title_2e4f06_idx'), models.Index(fields=['title', 'status'], name='portfolio_p_title_79e611_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('live_demo_url__isnull', False), ('source_code_url__isnull', False), _connector='OR'), name='project_requires_at_least_one_link'), models.UniqueConstraint(fields=('profile', 'title'), name='unique_project_title_per_profile')],
            },
        ),
    ]
