# Generated by Django 6.0.7 on 2026-08-04 00:45

import core.models
import django.core.validators
import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=portfolio.models.image_upload_path, validators=[core.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['project', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('project', 'display_order'), name='unique_project_image_order')],
            },
        ),
    ]
