# Generated by Django 6.0.7 on 2026-08-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_skills'),
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.profile')),
            ],
            options={
                'ordering': ('-start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('currently_working', True), ('end_date__isnull', True)), ('currently_working', False), _connector='OR'), name='experience_currently_working_no_end_date'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='experience_start_before_end')],
            },
        ),
    ]
