# Generated by Django 6.0.7 on 2026-08-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_skills'),
        ('portfolio', '0005_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['project', 'display_order'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('-start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='education_start_before_end')],
            },
        ),
    ]
