# Generated by Django 6.0.7 on 2026-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Unique SEO-friendly slug generated automatically from the project title.', max_length=255, unique=True),
        ),
    ]
