# Generated by Django 6.0.7 on 2026-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_about_profile_about'),
        ('portfolio', '0007_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_requires_at_least_one_link',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('live_demo_url__isnull', False), ('source_code_url__isnull', False), _connector='OR'), name='project_requires_at_least_one_link'),
        ),
    ]
